
export default {
    language: {
        zh: "Chinese",
        en: "English"
    },
    login: {
        accountInputTipsText: "Please enter account",
        passwordInputTipsText: "Please enter password",
        loginButtonText: "Log in",
        accountInputIllegalText: "Please enter a valid phone number",
        passwordInputIllegalText: "Password length must be within 8-20 characters, and cannot contain special characters and spaces",
        loginSuccessNotificationText: "Login successful",
        loginFailedNotificationText: "Login failed",
        requestFailedText: "Request failed",
        loginDataInvalidText: "Login data is illegal!"
    },
    appManagement: {
        backButtonText: "Back",
        titleText: "AppManagement",
        uploadPackageDialogTitleText: "App Package Upload",
        uploadPackageDialogFormFileNameItemText: "AppFile",
        uploadPackageDialogFormAppNameItemText: "AppName",
        uploadPackageDialogFormAppVersionItemText: "AppVersion",
        uploadPackageDialogFormAppSystemItemText: "AppSystem",
        uploadPackageDialogFormAppProgressItemText: "AppProgress",
        uploadPackageDialogFormAppProgressItemRadioButton0Text: "Final",
        uploadPackageDialogFormAppProgressItemRadioButton1Text: "Beta",
        uploadPackageDialogFormAppDescriptionItemText: "AppDescription",
        uploadPackageDialogCancelButtonText: "Cancel",
        uploadPackageDialogUploadButtonText: "Upload",

        updatePackageDialogTitleText: "App Package Update",
        updatePackageDialogFormAppIdItemText: "AppId",
        updatePackageDialogFormFileNameItemText: "AppFile",
        updatePackageDialogFormAppNameItemText: "AppName",
        updatePackageDialogFormAppVersionItemText: "AppVersion",
        updatePackageDialogFormAppSystemItemText: "AppSystem",
        updatePackageDialogFormAppProgressItemText: "AppProgress",
        updatePackageDialogFormAppProgressItemRadioButton0Text: "Final",
        updatePackageDialogFormAppProgressItemRadioButton1Text: "Beta",
        updatePackageDialogFormAppDescriptionItemText: "AppDescription",
        updatePackageDialogCancelButtonText: "Cancel",
        updatePackageDialogUpdateButtonText: "Update",

        appListTableAppIconColumnText: "AppIcon",
        appListTableAppIDColumnText: "AppID",
        appListTableAppNameColumnText: "AppName",
        appListTableAppVersionColumnText: "AppVersion",
        appListTableUploadTimeColumnText: "UploadTime",
        appListTableUploadAccountColumnText: "UploadAccount",
        appListTableOperationsColumnText: "Operations",
        appListTableOperationsColumnUpdateButtonText: "Update",

        searchInputSelectTipsText: "Select",
        searchInputSelectOption0Text: "AppName",
        searchInputSelectOption1Text: "AppID",
        searchInputSelectOption2Text: "UploadAccount",

        uploadPackageButtonText: "Upload",
        deletePackageButtonText: "Delete",

        uploadPackageRulesFileNameMessageText: "The uploaded file cannot be empty",
        uploadPackageRulesAppNameMessageText: "App name cannot be empty",
        uploadPackageRulesAppVersionMessageText: "App version cannot be empty",
        uploadPackageRulesAppSystemMessageText: "App system not selected",
        uploadPackageRulesAppProgressMessageText: "App progress not selected",
        uploadPackageRulesAppDescriptionMessageText: "App description cannot be empty",

        updatePackageRulesAppIdMessageText: "AppId cannot be empty",
        updatePackageRulesFileNameMessageText: "The uploaded file cannot be empty",
        updatePackageRulesAppNameMessageText: "App name cannot be empty",
        updatePackageRulesAppVersionMessageText: "App version cannot be empty",
        updatePackageRulesAppSystemMessageText: "App system not selected",
        updatePackageRulesAppProgressMessageText: "App progress not selected",
        updatePackageRulesAppDescriptionMessageText: "App description cannot be empty",

        updateFileSelectErrorMessageText: "The system type of the update package must be the same",
        uploadPackageSuccessNotificationText: "Upload App successfully",
        uploadPackageErrorNotificationText: "Failed to upload App",
        updatePackageSuccessNotificationText: "Update App successfully",
        updatePackageErrorNotificationText: "Failed to update App",
        deletePackageSelectErrorMessageText: "Delete item not selected",
        deletePackageErrorNotificationText: "Failed to delete app",

        obtainAppListErrorNotificationText: "Failed to get App list",
        
        searchAppListErrorMessageText: "Incomplete search information",
    },
    userManagement: {
        backButtonText: "Back",
        titleText: "UserManagement",

        addUserDialogTitleText: "Add User",
        addUserDialogFormNameItemText: "Username",
        addUserDialogFormAccountItemText: "Account",
        addUserDialogFormPasswordItemText: "Password",
        addUserDialogFormPermissionItemText: "Permission",
        addUserDialogFormPermissionItemTipsText: "Select",
        addUserDialogFormPermissionItemOption0Text: "Administrator",
        addUserDialogFormPermissionItemOption1Text: "Tester",
        addUserDialogFormPermissionItemOption2Text: "Experiencer",
        addUserDialogCancelButtonText: "Cancel",
        addUserDialogAddButtonText: "Add",

        updatePermissionDialogTitleText: "Update Permission",
        updatePermissionDialogFormAccountItemText: "Account",
        updatePermissionDialogFormPermissionItemText: "Permission",
        updatePermissionDialogFormPermissionItemTipsText: "Select",
        updatePermissionDialogFormPermissionItemOption0Text: "Administrator",
        updatePermissionDialogFormPermissionItemOption1Text: "Tester",
        updatePermissionDialogFormPermissionItemOption2Text: "Experiencer",
        updatePermissionDialogCancelButtonText: "Cancel",
        updatePermissionDialogUpdateButtonText: "Update",

        userListTableAvatarColumnText: "Avatar",
        userListTableAccountColumnText: "Account",
        userListTableNameColumnText: "Username",
        userListTablePermissionColumnText: "Permission",
        userListTableOperationsColumnText: "Operations",
        userListTableOperationsColumnUpdateButtonText: "UpdatePermission",

        searchInputTipsText: "Please enter username or account",

        addUserButtonText: "Add User",
        deleteUserButtonText: "Delete User",

        addUserFormRulesNameMessage0Text: "Username can not be empty",
        addUserFormRulesNameMessage1Text: "Username must be within 2-24 characters and cannot contain special characters and spaces",
        addUserFormRulesAccountMessage0Text: "Account cannot be empty",
        addUserFormRulesAccountMessage1Text: "Please enter a valid phone number",
        addUserFormRulesPasswordMessage0Text: "Password can not be blank",
        addUserFormRulesPasswordMessage1Text: "Password length must be within 8-20 characters, and cannot contain special characters and spaces",
        addUserFormRulesPermissionMessage0Text: "Permission not selected",

        updatePermissionFormRulesAccountMessage0Text: "Account cannot be empty",
        updatePermissionFormRulesAccountMessage1Text: "Please enter a valid phone number",
        updatePermissionFormRulesPermissionMessage0Text: "Permission not selected",
        
        searchUserListErrorMessageText: "Search information cannot be empty",
        addUserErrorNotificationText: "Failed to add user",
        updatePermissionErrorNotificationText: "Failed to update permissions",
        deleteUserErrorMessageText: "Delete item not selected",
        deleteUserErrorNotificationText: "Failed to delete user",
        administratorPermissionText: "Administrator",
        testerPermissionText: "Tester",
        experiencerPermissionText: "Experiencer",
        obtainUserListErrorNotificationText: "Failed to get user list",
    }
}