
export default {
    language: {
        zh: "中文",
        en: "英文"
    },
    login: {
        accountInputTipsText: "请输入账号",
        passwordInputTipsText: "请输入密码",
        loginButtonText: "登录",
        accountInputIllegalText: "请输入正确的手机号",
        passwordInputIllegalText: "密码长度必须在8-20位以内, 且不能包含特殊字符和空格号",
        loginSuccessNotificationText: "登录成功",
        loginFailedNotificationText: "登录失败",
        requestFailedText: "请求失败",
        loginDataInvalidText: "登录数据不合法！"
    },
    appManagement: {
        backButtonText: "返回",
        titleText: "App管理",
        uploadPackageDialogTitleText: "App包上传",
        uploadPackageDialogFormFileNameItemText: "App文件",
        uploadPackageDialogFormAppNameItemText: "App名称",
        uploadPackageDialogFormAppVersionItemText: "App版本",
        uploadPackageDialogFormAppSystemItemText: "App系统",
        uploadPackageDialogFormAppProgressItemText: "App进度",
        uploadPackageDialogFormAppProgressItemRadioButton0Text: "正式版",
        uploadPackageDialogFormAppProgressItemRadioButton1Text: "测试版",
        uploadPackageDialogFormAppDescriptionItemText: "App描述",
        uploadPackageDialogCancelButtonText: "取消",
        uploadPackageDialogUploadButtonText: "上传",

        updatePackageDialogTitleText: "App包更新",
        updatePackageDialogFormAppIdItemText: "AppId",
        updatePackageDialogFormFileNameItemText: "App文件",
        updatePackageDialogFormAppNameItemText: "App名称",
        updatePackageDialogFormAppVersionItemText: "App版本",
        updatePackageDialogFormAppSystemItemText: "App系统",
        updatePackageDialogFormAppProgressItemText: "App进度",
        updatePackageDialogFormAppProgressItemRadioButton0Text: "正式版",
        updatePackageDialogFormAppProgressItemRadioButton1Text: "测试版",
        updatePackageDialogFormAppDescriptionItemText: "App描述",
        updatePackageDialogCancelButtonText: "取消",
        updatePackageDialogUpdateButtonText: "更新",

        appListTableAppIconColumnText: "图标",
        appListTableAppIDColumnText: "AppID",
        appListTableAppNameColumnText: "名称",
        appListTableAppVersionColumnText: "版本",
        appListTableUploadTimeColumnText: "上传时间",
        appListTableUploadAccountColumnText: "上传者",
        appListTableOperationsColumnText: "操作",
        appListTableOperationsColumnUpdateButtonText: "更新",

        searchInputSelectTipsText: "选择",
        searchInputSelectOption0Text: "App名称",
        searchInputSelectOption1Text: "AppID",
        searchInputSelectOption2Text: "上传者",

        uploadPackageButtonText: "上传",
        deletePackageButtonText: "删除",

        uploadPackageRulesFileNameMessageText: "上传的文件不能为空",
        uploadPackageRulesAppNameMessageText: "App名称不能为空",
        uploadPackageRulesAppVersionMessageText: "App版本不能为空",
        uploadPackageRulesAppSystemMessageText: "App系统未选择",
        uploadPackageRulesAppProgressMessageText: "App进度未选择",
        uploadPackageRulesAppDescriptionMessageText: "App描述不能为空",

        updatePackageRulesAppIdMessageText: "AppId不能为空",
        updatePackageRulesFileNameMessageText: "上传的文件不能为空",
        updatePackageRulesAppNameMessageText: "App名称不能为空",
        updatePackageRulesAppVersionMessageText: "App版本不能为空",
        updatePackageRulesAppSystemMessageText: "App系统未选择",
        updatePackageRulesAppProgressMessageText: "App进度未选择",
        updatePackageRulesAppDescriptionMessageText: "App描述不能为空",

        updateFileSelectErrorMessageText: "更新包的系统类型必须一致",
        uploadPackageSuccessNotificationText: "上传App成功",
        uploadPackageErrorNotificationText: "上传App失败",
        updatePackageSuccessNotificationText: "更新App成功",
        updatePackageErrorNotificationText: "更新App失败",
        deletePackageSelectErrorMessageText: "未选择删除项",
        deletePackageErrorNotificationText: "删除App失败",

        obtainAppListErrorNotificationText: "获取App列表失败",
        
        searchAppListErrorMessageText: "搜索信息不完整",
    },
    userManagement: {
        backButtonText: "返回",
        titleText: "用户管理",

        addUserDialogTitleText: "添加用户",
        addUserDialogFormNameItemText: "用户名",
        addUserDialogFormAccountItemText: "账号",
        addUserDialogFormPasswordItemText: "密码",
        addUserDialogFormPermissionItemText: "权限",
        addUserDialogFormPermissionItemTipsText: "选择",
        addUserDialogFormPermissionItemOption0Text: "管理员",
        addUserDialogFormPermissionItemOption1Text: "测试员",
        addUserDialogFormPermissionItemOption2Text: "体验员",
        addUserDialogCancelButtonText: "取消",
        addUserDialogAddButtonText: "添加",

        updatePermissionDialogTitleText: "更新权限",
        updatePermissionDialogFormAccountItemText: "账号",
        updatePermissionDialogFormPermissionItemText: "权限",
        updatePermissionDialogFormPermissionItemTipsText: "选择",
        updatePermissionDialogFormPermissionItemOption0Text: "管理员",
        updatePermissionDialogFormPermissionItemOption1Text: "测试员",
        updatePermissionDialogFormPermissionItemOption2Text: "体验员",
        updatePermissionDialogCancelButtonText: "取消",
        updatePermissionDialogUpdateButtonText: "更新",

        userListTableAvatarColumnText: "头像",
        userListTableAccountColumnText: "账号",
        userListTableNameColumnText: "用户名",
        userListTablePermissionColumnText: "权限",
        userListTableOperationsColumnText: "操作",
        userListTableOperationsColumnUpdateButtonText: "更新权限",

        searchInputTipsText: "请输入用户名或账号",

        addUserButtonText: "添加用户",
        deleteUserButtonText: "删除用户",

        addUserFormRulesNameMessage0Text: "用户名不能为空",
        addUserFormRulesNameMessage1Text: "用户名长度必须在2-24位以内, 且不能包含特殊字符和空格号",
        addUserFormRulesAccountMessage0Text: "账号不能为空",
        addUserFormRulesAccountMessage1Text: "请输入正确的手机号",
        addUserFormRulesPasswordMessage0Text: "密码不能为空",
        addUserFormRulesPasswordMessage1Text: "密码长度必须在8-20位以内, 且不能包含特殊字符和空格号",
        addUserFormRulesPermissionMessage0Text: "权限未选择",

        updatePermissionFormRulesAccountMessage0Text: "账号不能为空",
        updatePermissionFormRulesAccountMessage1Text: "请输入正确的手机号",
        updatePermissionFormRulesPermissionMessage0Text: "权限未选择",
        
        searchUserListErrorMessageText: "搜索信息不能为空",
        addUserErrorNotificationText: "添加用户失败",
        updatePermissionErrorNotificationText: "更新权限失败",
        deleteUserErrorMessageText: "未选择删除项",
        deleteUserErrorNotificationText: "删除用户失败",
        administratorPermissionText: "管理员",
        testerPermissionText: "测试员",
        experiencerPermissionText: "体验员",
        obtainUserListErrorNotificationText: "获取用户列表失败",
    }
}